#!/bin/bash
CONTENTDIR=`pwd`
TIMEOUT=60
SLEEP=5
exitcode=1
EXISTS=$(sudo docker ps -a | grep landshark-jenkins)

if [ -n "${EXISTS}" ]; then
	echo "The landshark-jenkins container is already created."
	echo "If you would like to recreate the container, run jenkins-delete first"
	echo "Starting container"
	sudo docker start landshark-jenkins
else
	sudo docker run -p 5777:8080 -p 50000:50000 --name "landshark-jenkins" -v ${CONTENTDIR}/..:/var/jenkins_home/scripts -d cloudsurgeon/landshark-jenkins:latest

	RETRY_COUNT=0
	until [ $exitcode -eq 0 ]; do
		curl -s http://linuxtarget:5777 | grep 'New Item' &>> /dev/null
		exitcode=$?
		echo "Waiting for Jenkins to finish starting (up to ${TIMEOUT} seconds)"
		((RETRY_COUNT++))
		if [ ${RETRY_COUNT} -eq $((TIMEOUT/SLEEP)) ]; then
			echo "Timeout while waiting for Jenkins to start"
			exit 1
		fi
		sleep ${SLEEP}
	done

	${CONTENTDIR}/add_create_oracle_vdb_job.sh
	${CONTENTDIR}/add_create_oraclexe_vdb_job.sh
	${CONTENTDIR}/add_snapshot_job.sh
	${CONTENTDIR}/add_delete_job.sh
	${CONTENTDIR}/add_container_refresh_job.sh
	${CONTENTDIR}/add_bookmark_container_job.sh
	${CONTENTDIR}/add_employee_xe_build_test_job.sh
	${CONTENTDIR}/add_build_pipeline_plugin_job.sh
	${CONTENTDIR}/add_CI_Pipeline_view.sh
	echo "Jenkins setup complete"
fi
echo 'You can access jenkins at http://<linuxtarget ip>:5777'
